apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-webhook-template
  labels:
    app: k8s-webhook-template
    kind: mutator
webhooks:
  - name: addlable.neteric.top
    # Avoid chicken-egg problem with our webhook deployment.
    objectSelector:
      matchExpressions:
      - key: app
        operator: NotIn
        values: ["k8s-webhook-template"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      # service:
      #   name: k8s-webhook-template
      #   namespace: k8s-webhook-template
      #   path: /mutate-pod
      url: https://192.168.254.2:8443/mutate-pod
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVhVENDQXRHZ0F3SUJBZ0lRRU1FdjdtVlQwblNqM1Q5b1R4UlM2ekFOQmdrcWhraUc5dzBCQVFzRkFEQjcKTVI0d0hBWURWUVFLRXhWdGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZ1EwRXhLREFtQmdOVkJBc01IMjVsZEdWeQphV05BUTJoaGIyUmxUV0ZqUW05dmF5MVFjbTh1Ykc5allXd3hMekF0QmdOVkJBTU1KbTFyWTJWeWRDQnVaWFJsCmNtbGpRRU5vWVc5a1pVMWhZMEp2YjJzdFVISnZMbXh2WTJGc01CNFhEVEkwTURreU56QTFOVGN3TmxvWERUSTIKTVRJeU56QTFOVGN3Tmxvd1dqRW5NQ1VHQTFVRUNoTWViV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJR05sY25ScApabWxqWVhSbE1TOHdMUVlEVlFRTERDWnVaWFJsY21salFFTm9ZVzlrWlUxaFkwSnZiMnN0VUhKdkxteHZZMkZzCklDaERhR0Z2S1RDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHFDcHFONXBIZ28KLzNjZm1aMlZab3A0YTZLQWk0Y0tTWGlIbjB1N3hsLzkvYjRMUXhUT25EZXFQNmtMYUVxazhvcmRPZUs2VllKWApyVE1TWkJZODJIQURYSnYrTDNISGZQR1lUZGJiYnMzNzJzdUNYMXRnNjZaQUNNMElRK2dpMTZCRDZjZDhRVTRYCi9ka0kvTjNDL2lnaGZkUkJtMk5TZFB0RjN1VWs2UnVUaHhHMnZLc2xoWG56cUJENnhaOTZIUm51TGcxN0xSZmwKcW5FREdvcGRpeE9td2N4TU0yZzc5dzhSMFR2cWhIdzNSdXZIeFVnYU9lNGZhMlRmWUpJYkJ4NSs1YkRpbWhDTwo4eHAzSlJrSGlxcVJRYUlCUWVwVGhaQU5mVzM5eFdiTGw1dFl3ejl1QlByWEYvczJRUXhhSlREYzVyVktNU1ZPCkFMR2pDTDhHQjJzQ0F3RUFBYU9CaVRDQmhqQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3SHdZRFZSMGpCQmd3Rm9BVVUwbkthWE1scC9XNTgreE1Gb2ljazBJejdKMHdQZ1lEVlIwUgpCRGN3TllJdGF6aHpMWGRsWW1odmIyc3RkR1Z0Y0d4aGRHVXVhemh6TFhkbFltaHZiMnN0ZEdWdGNHeGhkR1V1CmMzWmpod1RBcVA0Q01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQmdRREZNTHkyNXF4UnQ1REhqeHd5UFh1S2FJVEYKMG1uelBLeUFwZGtNbGZFVjQ5azVMa3I5U1d1ZW5yNU9IN2NuakRSdFNUN1dMK3Y2UlZFcGNXQ3BtdXVqZFh0bgpEWHd3Uy8wMm5YWGVjQzQxLzN0ZnNZeEtwOHVFT1ArZnlwOEJBUHowYWZxdXpZY252NTFyZWhDcFIwQUtpL0pTCncwZ3daWWxVaFRUMHlWRTJodjY1RUFNOXlPemdHakJsTUN6djBhcEhlYWtlNDFPdnVxcjdxUlRWYzBXWENNKzYKSnlscVhYcHYyOHlsT2JlZjVMV3htVGNJb3B4ZEpZQzFwbVc1V1BoZjZqNUxWa0h2bHFxY3dTYytxN1lZc0tHOApiNitpUnF6dE12OXoybFVkZ1ZjczU2S1huczVyVWRmS1Q5OFJvWjQwdnoweW0wb2tvWi81SU5nKzcxS0hFRnZ6CkVmQURrcUVOTENTeXlKdTVrYm4yK0haN1JpWnpCTkxoOEhaVURPZVBjNjhWcUVrVUI2YytCdGVialBWUExNSy8KNUdYemFMa2lhZkRxMUgxSGRyZ2RaNkJSU0V4a1BEQTF2bXluZVJFTkVaMU96dVpjckFyZGhiS2crbTMxTDM5ZwoyYllZc3JoVTUxcHAvSUJKVWtaSTNXc1pnYU1yNUZXVzJNT3BWQ3c9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["pods"]


---
# apiVersion: admissionregistration.k8s.io/v1
# kind: ValidatingWebhookConfiguration
# metadata:
#   name: k8s-webhook-template-webhook
#   labels:
#     app: k8s-webhook-template-webhook
#     kind: validator
# webhooks:
#   - name: podvalidate.neteric.top
#     admissionReviewVersions: ["v1"]
#     sideEffects: None
#     clientConfig:
#       service:
#         name: k8s-webhook-template
#         namespace: k8s-webhook-template
#         path: /validate-pod
#       caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVZVENDQXNtZ0F3SUJBZ0lSQUpZMUM0WGJUeHBkemlrVDVYcDRCbU13RFFZSktvWklodmNOQVFFTEJRQXcKZXpFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNU2d3SmdZRFZRUUxEQjl1WlhSbApjbWxqUUVOb1lXOWtaVTFoWTBKdmIyc3RVSEp2TG14dlkyRnNNUzh3TFFZRFZRUUREQ1p0YTJObGNuUWdibVYwClpYSnBZMEJEYUdGdlpHVk5ZV05DYjI5ckxWQnlieTVzYjJOaGJEQWVGdzB5TkRBNU1qUXdOalF5TURSYUZ3MHkKTmpFeU1qUXdOalF5TURSYU1Gb3hKekFsQmdOVkJBb1RIbTFyWTJWeWRDQmtaWFpsYkc5d2JXVnVkQ0JqWlhKMAphV1pwWTJGMFpURXZNQzBHQTFVRUN3d21ibVYwWlhKcFkwQkRhR0Z2WkdWTllXTkNiMjlyTFZCeWJ5NXNiMk5oCmJDQW9RMmhoYnlrd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNXem83dnhnN2cKZVliTlJrbjBZWEN2aTc5WDY0Nm9hT2NSd242TGVZYkFrY2JjbUhlc3UzSFZBdWIzd09PaUNoakZhbEpNRlRHZQpRemkzTW94ZUI3RXNsSUFCRmdBQ21XbkhsM09LOHRieTljS0dkWXJmaDNWVFQxM1V5LytzTXVNWU5pSE81L3EwCmptMkJmUDdlZjBoSncwVUNZREVWNXFkRExLZnY2eDc3SkhiUS95eVBYYW41Q09RTElES08zNzFUYkZWZ3k3anYKdFJJZGo0ci9vZSt0VDkrSXFKR0dWOVlEN05XNjhHWjcrNnNZbzhOQTlBbkRBZllocjhQTHBnamxINjZCZExpSAp5UjJnblpjUFF6MkV6VU9GdUZFRHN0cHltZ0dHc3docm1rK1FscW5ZNHA0Mkl1WlRxU1dtOFZTdUpidEZYRFI3CldHcHlDUkUzYlovNUFnTUJBQUdqZ1lBd2ZqQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3SHdZRFZSMGpCQmd3Rm9BVVUwbkthWE1scC9XNTgreE1Gb2ljazBJejdKMHdOZ1lEVlIwUgpCQzh3TFlJcmF6aHpMWGRsWW1odmIyc3RaWGhoYlhCc1pTNXJPSE10ZDJWaWFHOXZheTFsZUdGdGNHeGxMbk4yCll6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FZRUFVOWF5SXNkV3RIT2pveHpRWXdMN29KUFdWczF4VHh1b09UanEKYnA1Y0VVa1c2RW9BSU40SFUxVTZWbVNzSWRUcG1lRVk5RXU1NndNWndYVXlOUUdTMERuWFFHMzhHUWxEdGc4RApjVVNZUUlrY0tOZW5wYXBEUDk3VE0xMkJsUWRRODd0VFdwcVZSem5oQ3A3VUpnZnZ5ZUpyZ0s5aTRHOUkwNHp3Ck9NYm14Z1Qrc2FEd21ZWFRZa2lzOVl3ak5WMEFXckpwZmtpdjZFUHdIVFhvU2FlbW04YnNCMlIvVFhOVUFKMWsKa1RaT0RoaWxyMDRpUWJtWnJ5anRPajd6TTFsQmF2b3NEeExJUTdKSys5clFQL3FxNVVwaWNKSlZ5d3BUUjFlZwptNVlhSFpZZkNUM0RlM1FNRkZON0N3RUlHczMzZEIxd05wR21EQmVucWc2OVpDRXd2OVpSWXR3WmdvVlJzaTRpCnFpMi9IeWlBc1h2OStXZCtXbHFLakl3c3NvalVWN1dTeVJUNWlFZFMzTEVqKzh2YWFSU1pja2F6c0lrTUdDOVYKWkdjUzdWU0JVV3RYMndoanNJMTRhQnJpM3gybnUxZ2pOcVNuN2FzVFBpL3ZDTlo2NlV4bmdteXhOSlNzNytKWQpXbHc0aDdMTUM1bFhtMzhUYXF1T3ljRTFneXp3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#     rules:
#       - operations: ["CREATE", "UPDATE"]
#         apiGroups: ["*"]
#         apiVersions: ["*"]
#         resources: ["pod"]