apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-webhook-template
  labels:
    app: k8s-webhook-template
    kind: mutator
webhooks:
  - name: addlable.neteric.top
    # Avoid chicken-egg problem with our webhook deployment.
    objectSelector:
      matchExpressions:
      - key: app
        operator: NotIn
        values: ["k8s-webhook-template"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: k8s-webhook-template
        namespace: k8s-webhook-template
        path: /mutate-deployment
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVZekNDQXN1Z0F3SUJBZ0lRYUZUcEVUVGg4MVBickhyUWQ2MndPREFOQmdrcWhraUc5dzBCQVFzRkFEQjcKTVI0d0hBWURWUVFLRXhWdGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZ1EwRXhLREFtQmdOVkJBc01IMjVsZEdWeQphV05BUTJoaGIyUmxUV0ZqUW05dmF5MVFjbTh1Ykc5allXd3hMekF0QmdOVkJBTU1KbTFyWTJWeWRDQnVaWFJsCmNtbGpRRU5vWVc5a1pVMWhZMEp2YjJzdFVISnZMbXh2WTJGc01CNFhEVEkwTURreU5URTBNRFl5TWxvWERUSTIKTVRJeU5URTBNRFl5TWxvd1dqRW5NQ1VHQTFVRUNoTWViV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJR05sY25ScApabWxqWVhSbE1TOHdMUVlEVlFRTERDWnVaWFJsY21salFFTm9ZVzlrWlUxaFkwSnZiMnN0VUhKdkxteHZZMkZzCklDaERhR0Z2S1RDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTk5UaHFJZXJ2clUKNTk5WkpVREtTT0tENGxzZmFTL2NpMUg5V1R4bTJmWkdnWkttTnhqRG5ESkRqbU1Cb3ZDMHE3eTN5VDdURnBDRAowMDhFZkMrWHVFbFN5QzNhMXZsRkxwd0FGdk81VlYzWG4rTllJN0JnVmZjYzVmbkdQMERQdFI0S3hyYmNBbmJvCjRIYlpvLzlsemQ1cEtLWExoRUVJMlZTSjUzWU92aDZqT2RYajJjOHlSMGZSa3hya0xHN0JPeGlmbm5oMGlWUFYKS280ZnYrWVdoNDlCT3VieDhoS0R3a09uMXRoSnNEVVlkRGVjaEF1NzhHdnZZRXRpYjQydEVGRU5FT2JxZi80OAppdDFPU2lKV2tldzhVcDZsTEk4MVh0Ym42L3pEeVIxWnhpK2RRVUxwaXFsckxjWktsZ0o4SjRRV0dhU3pFOHpoCkZ0SkRpUTVRMXpFQ0F3RUFBYU9CZ3pDQmdEQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3SHdZRFZSMGpCQmd3Rm9BVVUwbkthWE1scC9XNTgreE1Gb2ljazBJejdKMHdPQVlEVlIwUgpCREV3TDRJdGF6aHpMWGRsWW1odmIyc3RkR1Z0Y0d4aGRHVXVhemh6TFhkbFltaHZiMnN0ZEdWdGNHeGhkR1V1CmMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJnUUE4RWZCWmZJQ3pYeUkxM1dFNXJHbFNqQUY5bFUrRFUyR2sKdWE5L1h5S1l3WDJ0cm85aDR3dDdJb1Z6elBRK2VuM1AxMnh6MThWcWtaNGZacHM2eHd6TVZHZEErYW1BaEtlQgozN0J0eWQ2ZGQ5OUZaMDREcGw0N2RHK3IrSnRCTjFRODBZMEVweGtYcUpHWTlSVi9TT09abWM2ZC84VGpDS3JpCmxIMWhtNnJlV1NrUFhDRG9LcSswbmZIelhkeVhNZm1qSDB2TUE3OGF2MFp0Zmhod2tML0tLVy9iSzRDYThyVUcKRUJ3VUxJQzFwNXZxQWVaR1NiNjUxM3prSmhxay9UV3NDSXhYTGhqMU5WYjJhYlUzelhsS1dvR2Q0UDFvZDhpagpmSkZrRTd0Wm00N256SDUwcEFqbnlSd0t6cG04dnhoSEF6SjZ6bndMRnFwV0NrSkZMTVNscWlFL2VOcnVUNFhvCnh2ODNnWGNuWTUwM2VRVTRPaHl4OTVkU2dHQlQ3ZkpsWksrOHNnWFZDT0dwL3dEYnVhenhDT3pCUWdpZ2RTemIKSjEzNmlFUG8zTkVpYXZxZTFrUkpTSzlKaWNONllTNE5ySmJsTkhSWWdQVkpBVDg1WG5ERCtERTR2ekc2ZjJRdApNSk9VaXBFY3JKRjJSb1dTb3lFekR4RldycThMeTdZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["deploymens"]


---
# apiVersion: admissionregistration.k8s.io/v1
# kind: ValidatingWebhookConfiguration
# metadata:
#   name: k8s-webhook-template-webhook
#   labels:
#     app: k8s-webhook-template-webhook
#     kind: validator
# webhooks:
#   - name: podvalidate.neteric.top
#     admissionReviewVersions: ["v1"]
#     sideEffects: None
#     clientConfig:
#       service:
#         name: k8s-webhook-template
#         namespace: k8s-webhook-template
#         path: /validate-pod
#       caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVZVENDQXNtZ0F3SUJBZ0lSQUpZMUM0WGJUeHBkemlrVDVYcDRCbU13RFFZSktvWklodmNOQVFFTEJRQXcKZXpFZU1Cd0dBMVVFQ2hNVmJXdGpaWEowSUdSbGRtVnNiM0J0Wlc1MElFTkJNU2d3SmdZRFZRUUxEQjl1WlhSbApjbWxqUUVOb1lXOWtaVTFoWTBKdmIyc3RVSEp2TG14dlkyRnNNUzh3TFFZRFZRUUREQ1p0YTJObGNuUWdibVYwClpYSnBZMEJEYUdGdlpHVk5ZV05DYjI5ckxWQnlieTVzYjJOaGJEQWVGdzB5TkRBNU1qUXdOalF5TURSYUZ3MHkKTmpFeU1qUXdOalF5TURSYU1Gb3hKekFsQmdOVkJBb1RIbTFyWTJWeWRDQmtaWFpsYkc5d2JXVnVkQ0JqWlhKMAphV1pwWTJGMFpURXZNQzBHQTFVRUN3d21ibVYwWlhKcFkwQkRhR0Z2WkdWTllXTkNiMjlyTFZCeWJ5NXNiMk5oCmJDQW9RMmhoYnlrd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNXem83dnhnN2cKZVliTlJrbjBZWEN2aTc5WDY0Nm9hT2NSd242TGVZYkFrY2JjbUhlc3UzSFZBdWIzd09PaUNoakZhbEpNRlRHZQpRemkzTW94ZUI3RXNsSUFCRmdBQ21XbkhsM09LOHRieTljS0dkWXJmaDNWVFQxM1V5LytzTXVNWU5pSE81L3EwCmptMkJmUDdlZjBoSncwVUNZREVWNXFkRExLZnY2eDc3SkhiUS95eVBYYW41Q09RTElES08zNzFUYkZWZ3k3anYKdFJJZGo0ci9vZSt0VDkrSXFKR0dWOVlEN05XNjhHWjcrNnNZbzhOQTlBbkRBZllocjhQTHBnamxINjZCZExpSAp5UjJnblpjUFF6MkV6VU9GdUZFRHN0cHltZ0dHc3docm1rK1FscW5ZNHA0Mkl1WlRxU1dtOFZTdUpidEZYRFI3CldHcHlDUkUzYlovNUFnTUJBQUdqZ1lBd2ZqQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0V3WURWUjBsQkF3d0NnWUkKS3dZQkJRVUhBd0V3SHdZRFZSMGpCQmd3Rm9BVVUwbkthWE1scC9XNTgreE1Gb2ljazBJejdKMHdOZ1lEVlIwUgpCQzh3TFlJcmF6aHpMWGRsWW1odmIyc3RaWGhoYlhCc1pTNXJPSE10ZDJWaWFHOXZheTFsZUdGdGNHeGxMbk4yCll6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FZRUFVOWF5SXNkV3RIT2pveHpRWXdMN29KUFdWczF4VHh1b09UanEKYnA1Y0VVa1c2RW9BSU40SFUxVTZWbVNzSWRUcG1lRVk5RXU1NndNWndYVXlOUUdTMERuWFFHMzhHUWxEdGc4RApjVVNZUUlrY0tOZW5wYXBEUDk3VE0xMkJsUWRRODd0VFdwcVZSem5oQ3A3VUpnZnZ5ZUpyZ0s5aTRHOUkwNHp3Ck9NYm14Z1Qrc2FEd21ZWFRZa2lzOVl3ak5WMEFXckpwZmtpdjZFUHdIVFhvU2FlbW04YnNCMlIvVFhOVUFKMWsKa1RaT0RoaWxyMDRpUWJtWnJ5anRPajd6TTFsQmF2b3NEeExJUTdKSys5clFQL3FxNVVwaWNKSlZ5d3BUUjFlZwptNVlhSFpZZkNUM0RlM1FNRkZON0N3RUlHczMzZEIxd05wR21EQmVucWc2OVpDRXd2OVpSWXR3WmdvVlJzaTRpCnFpMi9IeWlBc1h2OStXZCtXbHFLakl3c3NvalVWN1dTeVJUNWlFZFMzTEVqKzh2YWFSU1pja2F6c0lrTUdDOVYKWkdjUzdWU0JVV3RYMndoanNJMTRhQnJpM3gybnUxZ2pOcVNuN2FzVFBpL3ZDTlo2NlV4bmdteXhOSlNzNytKWQpXbHc0aDdMTUM1bFhtMzhUYXF1T3ljRTFneXp3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#     rules:
#       - operations: ["CREATE", "UPDATE"]
#         apiGroups: ["*"]
#         apiVersions: ["*"]
#         resources: ["pod"]